name: tewo_tdk
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.0
  path_provider: ^2.1.2
  file_picker: ^8.1.7
  window_manager: ^0.4.3
  google_fonts: ^6.2.1
  provider: ^6.1.2
  uuid: ^4.5.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true
